#ifndef CONSTANTS_H
#define CONSTANTS_H

#define HEADER_SIZE 100

#define PAGE_SIZE_OFFSET 16

#define NO_OF_CELLS_OFFSET 3

#define DEFAULT_PAGE_SIZE 4096

#define TABLE_BTREE_LEAFCELL_HEADER 0x0d

#define TABLE_BTREE_INTERIORCELL_HEADER 0X05

#define INDEX_BTREE_LEAFCELL_HEADER 0X0a

#define INDEX_BTREE_INTERIORCELL_HEADER 0x02

#endif // CONSTANTS_H
